### ISSUE TITLE
Check all diagrams for licences and redraw them when necessary

### ISSUE THREAD

**Issue by anenadic** [carpentries-incubator/python-intermediate-development#1]
Many diagrams were borrowed from the Internet for quick inclusion in training materials and to make a point. Even though they come from free tutorials etc. some of them do not have an explicit licence attached which means they would need replacing/redrawing. There are comments in material where the images were borrowed from.

**Comment by steve-crouch** [comment]
Ensure that our images can be edited/reproduced.
