### ISSUE TITLE
Add direct instruction to commit requirements.txt file

### ISSUE THREAD

**Issue by bielsnohr** [carpentries-incubator/python-intermediate-development#103]
In the section about importing and exporting a virtual environment using a `requirements.txt` file (https://carpentries-incubator.github.io/python-intermediate-development/12-virtual-environments/index.html#exportingimporting-an-environment-with-pip), I think there should be an explicit instruction to commit the requirements.txt file to version control.

**Comment by anenadic** [comment]
There is an explicit command to commit the `requirements.txt` file, but it happens a bit later in the narrative (in episode https://carpentries-incubator.github.io/python-intermediate-development/14-collaboration-using-git/index.html) when we start using Git from the command line, after a short Git refresher. Perhaps this happens with a bit of a delay, but we do mention in virtual environment section that this file can and should be version controlled. I think giving the Git command here would be a bit out of context but we could add a note that this will be covered later. Would that be a satisfactory solution @bielsnohr?

**Comment by bielsnohr** [comment]
Yes, I think a quick note that we will handle the `requirements.txt` (and the `venv` folder for that matter) later on in git is worthwhile. I think the reason that this stuck out for me is that my terminal prompt reports uncommitted changes if I am located in a git repo directory, so it was nagging me until the git section :wink: 

There is a small pile of changes I have made to the course as a result of running it at my institution. I'm happy to fold this change in with those and submit a fairly large PR, or I am happy to submit a small independent PR for only this change.

**Comment by anenadic** [comment]
Thank you @bielsnohr. Congratulation on running the first independent pilot - I'll try to catch up with you soon to hear your impressions. Wrt updating the material - either way works - but more smaller PRs might be easier to review and will get merged in faster.
