### ISSUE TITLE
Feature Branch Software Development Workflow

### ISSUE THREAD

**Issue by p-j-smith** [carpentries-incubator/python-intermediate-development#105]
In the section `Git Branches` in the `Collaborative Software Development Using Git and GitHub` lesson, a description of git-flow states:

> we normally have a development branch (called `develop` or `dev` by convention) that we use for work-in-progress code. As we work on adding new features to the code, we create new feature branches that first get merged into `develop`, and then once thoroughly tested - can get merged into main.

This is perhaps slightly misleading. I suspect most projects would want code to be thoroughly tested before merging a feature branch into `develop`, and merge into main just before making a new release.

**Comment by anenadic** [comment]
Depends on the practice used in the team.
