### ISSUE TITLE
Mention Typer as well as Click

### ISSUE THREAD

**Issue by p-j-smith** [carpentries-incubator/python-intermediate-development#109]
At the end of the `MVC Revisted` section of the `Software Design` lesson, there is a suggestion to look into Click when creating a CLI. It might be worth also mentioning [Typer](https://typer.tiangolo.com/), which is built on top of Click and removes some of the boilerplate that you need to write.

P.S. thank you for creating this fantastic course! I really enjoyed the lesson Software Architecture and Design, especially the discussion of programming paradigms and the nice example of the MVC pattern (which I've been trying to get my head around recently).

**Comment by anenadic** [comment]
There is so many different things to mention so there is a worry that the course might balloon.
