### ISSUE TITLE
Tighten up language around Bash-like program in installation instructions

### ISSUE THREAD

**Issue by bielsnohr** [carpentries-incubator/python-intermediate-development#110]
In the [installation instructions for the command line program](https://carpentries-incubator.github.io/python-intermediate-development/setup.html#command-line-program), it states:

> You can use a command line program such as Bash. If you already have a command line program other than Bash - you can use that instead as none of the content of this workshop is specific to Bash.

This could be potentially misleading for learners, particularly on Windows if they think that `cmd` will be an appropriate alternative, because I am quite certain a number of the commands in the lesson will not work with `cmd`.  I would recommend something along the lines of:

> You can use a command line program that has similar syntax to Bash, although using Bash itself is recommended. The `cmd` command line in Windows is not suitable.

**Comment by anenadic** [comment]
Sounds good.
