### ISSUE TITLE
update recommended versions/dependencies to more something more current

### ISSUE THREAD

**Issue by smason** [carpentries-incubator/python-intermediate-development#111]
I've just been going through the course and noticed that it refers to some ancient Python versions.  E.g. [setup.md] says you "recommend using Python version 3.3+" which feels far too old, 3.3 is when `venv` was introduced, so at best that's the technical minimum not recommended, while [3.6 is EOL now](https://pythonspeed.com/articles/stop-using-python-3.6/).

It also seems useful to firmly point out that 2.7 is end-of-life/unsupported, rather than just saying "Things won't work well if you use Python 2".

https://snarky.ca/a-reverse-chronology-of-some-python-features/ might be a useful reference: it reminds me that f-strings were introduced back in 3.6, while 3.7 also has some nice things (I personally use `from __future__ import annotations` a lot as well as relying on `dict`s preserving order).

I also see that [_episodes/12-virtual-environments.md] mentions `virtualenv` (I switched to `venv` when I stopped using Python 2.7) and doesn't make any mention of more recent tools like [`poetry`](https://python-poetry.org/) or [`PDM`](https://pdm.fming.dev/).  PDM is probably too recent to include yet, but `poetry publish` might be nice to mention in section 4 somewhere.

I'm happy to turn these into pull request(s) but thought some discussion would be useful first.

[setup.md]: ../blob/gh-pages/setup.md#python-distribution
[_episodes/12-virtual-environments.md]: ../blob/gh-pages/_episodes/12-virtual-environments.md#managing-python-virtual-environments

**Comment by smangham** [comment]
@anenadic and I were discussing Python 2 in particular just the other day - we definitely think Python 2 needs some stronger discouragement. At the very least, running the course for mixed 2/3 users is going to make debugging harder. A straight up 'You cannot do this in Python 2' is probably too firm, as people trapped in Python 2 by their collaboration are probably more in need of good external advice than most, and almost all the examples will work in 2 anyway.

Switching 3.3 to 3.7 is probably the minimum as well, if that's the oldest non-EOL version?

Poetry is definitely worth including a mention of too in that section at the least.

**Comment by smason** [comment]
> Poetry is definitely worth including a mention of too in that section at the least.

had mentioned it to @bielsnohr but he thought it might be a bit advanced for this course, so I doubted including it

> Switching 3.3 to 3.7 is probably the minimum as well, if that's the oldest non-EOL version?

https://devguide.python.org/#status-of-python-branches might be a better reference for that, at least it's under python.org!  I haven't been keeping up myself, but seems that branches live for 5 years by default now, 2.7 is obviously a very special case

> A straight up 'You cannot do this in Python 2' is probably too firm

maybe saying something like:

>## Recommended Python Version
> For greatest compatibility we recommend using at least Python version 3.8, but any [supported version](https://devguide.python.org/#status-of-python-branches) should work (i.e. 3.7 onward).
> Specifically, we recommend upgrading from Python 2.7 wherever possible.  Continuing to use it will likely result in difficultly finding supported dependencies or syntax errors.

Maybe I should just turn this into a pull request!

**Comment by jag1g13** [comment]
We've actually got some content on Poetry that we've added to a custom version of this course that could be folded into the core here.

Here's the material we wrote previously: https://sabs-r3.github.io/software-engineering-day4/03-packaging/index.html

**Comment by smason** [comment]
@smangham thanks for putting that together so quickly.  sorry I didn't manage to respond before it was merged, it looks good to me.

it looks like a good improvement, especially the `ls` / `pip list` change

**Comment by smason** [comment]
@jag1g13's your description of packaging looks great, but would be quite a change from the existing course which doesn't seem to touch on packaging much beyond installing with pip, as far as I've noticed anyway

I was just thinking of adding it along side the existing pointers to venv & conda, in the virtual-environments document.  what other people think?

**Comment by anenadic** [comment]
Update to 3.8+

**Comment by jag1g13** [comment]
That's where we've put it in a modified version of this course, as a short episode on software packaging cut down from the materials I linked above

**Comment by smangham** [comment]
> Here is the link to the "other" version of the course, which includes the bits on Poetry, code reviews, etc. https://softwaresaved.github.io/az-intermediate-software-skills-course/35-software-release/index.html
Link's gone stale unfortunately. What was the task I've been assigned? Refresh the versions again, or is this related to moving to use the AZ-style Poetry/packaging section?

**Comment by anenadic** [comment]
> > Here is the link to the "other" version of the course, which includes the bits on Poetry, code reviews, etc. https://softwaresaved.github.io/az-intermediate-software-skills-course/35-software-release/index.html
> 
> Link's gone stale unfortunately. What was the task I've been assigned? Refresh the versions again, or is this related to moving to use the AZ-style Poetry/packaging section?

The correct link is: https://carpentries-incubator.github.io/python-intermediate-development/43-software-release/index.html

I think we have included the episode on poetry since this issue was opened so I do not see anything else to be done here, apart from maybe reviewing the episode on packaging to see if we ca include `poetry publish` @smangham.

**Comment by smangham** [comment]
I've not actually used `poetry publish` so I'll have to pass this over to someone else - very unlikely to have time to learn how to use it in the near future.

**Comment by anenadic** [comment]
We also need to see how much material this would add to an already full course - perhaps we could just link out to more documentation or see if anyone else in the team has an expertise in using poetry publish @steve-crouch @douglowe @bielsnohr @kkh451 ?

**Comment by anenadic** [comment]
Closed via #337
