### ISSUE TITLE
Briefly mention pytest support for unittest based tests

### ISSUE THREAD

**Issue by zmielko** [carpentries-incubator/python-intermediate-development#116]
In the episode "Automatically Testing Software" under the "What About Unit Testing in Other Languages?" section other python testing frameworks such as nose2 and unittest are mentioned. Would it be helpful to briefly indicate that unittest is part of the standard library and that one of the features of pytest is support for tests written for unittest? 

I ask because it may help preemptively address questions from students who may generally wish to prioritize use of the standard library over third party libraries for portability purposes.

**Comment by anenadic** [comment]
Will add a sentence to address this.
