### ISSUE TITLE
UKAEA pilot January - February 2022

### ISSUE THREAD

**Issue by anenadic** [carpentries-incubator/python-intermediate-development#121]
https://ukaea-rse-training.github.io/2022-01-25-ukaea-int-dev-online/ organised by @bielsnohr for the UKAEA.

**Comment by anenadic** [comment]
Any chance you can give us the number of attendees for this workshop please @bielsnohr ? Many thanks!

**Comment by bielsnohr** [comment]
Sorry for the delay. This was delivered to 15 people.
