### ISSUE TITLE
GitHub Action Build Matrix cancels all jobs

### ISSUE THREAD

**Issue by guyer** [carpentries-incubator/python-intermediate-development#124]
In [Continuous Integration for Automated Testing](https://carpentries-incubator.github.io/python-intermediate-development/23-continuous-integration-automated-testing/index.html), modifying the GitHub Action to implement a [Build Matrix](https://github.com/carpentries-incubator/python-intermediate-development/blob/2435e32168f60bcb754d789fa7181b6431f87965/_episodes/23-continuous-integration-automated-testing.md?plain=1#L215) results in the first job failing and then all subsequent jobs being cancelled:
- Following the current instructions produces a `venv` and `requirements.txt` for Python 3.9
- [build (ubuntu-latest, 3.7)](https://github.com/guyer/python-intermediate-inflammation/runs/5429806055?check_suite_focus=true#logs) fails with `ERROR: No matching distribution found for numpy==1.22.2`
- All subsequent jobs are cancelled: [`The job was canceled because "ubuntu-latest_3_7" failed.`](https://github.com/guyer/python-intermediate-inflammation/actions/runs/1936528918)

I'm new to GitHub Actions, although not to CIs, so I don't understand why the different matrix conditions depend on one another. I'd think the desired outcome is that all matrix variants run independently to conclusion.

The simple fix is to adjust the `python-version` build matrix to be consistent with the package versions in `requirements.txt`. I think, though, that it's a good demonstration to have a build matrix that runs obsolete configurations, as well newer than what the code was written for. Codes break all the time (mine do, anyway!) because external dependencies become unavailable or "upgrade" with some incompatible change. Testing for, recognizing, and addressing these situations are important skills for releasing robust software.

If I can figure out why all jobs get cancelled, I'll submit a patch that both addresses that and adds didactic about using the CI to test for configurations other than what the author used.

**Comment by thomaskileyukaea** [comment]
All jobs get cancelled because of default behavior of GitHub actions:

From [GitHub's documentation](https://docs.github.com/en/actions/using-jobs/using-a-matrix-for-your-jobs#handling-failures):

>  GitHub will cancel all in-progress and queued jobs in the matrix if any job in the matrix fails.

This can be changed by changing the `fail-fast` property:

```
...
    strategy:
      fail-fast: false
      matrix:
...
```

**Comment by anenadic** [comment]
This is useful to know, could add a note in the material or Instructor Notes.
