### ISSUE TITLE
Syntax highlighting in quiz

### ISSUE THREAD

**Issue by marklcrowe** [carpentries-incubator/python-intermediate-development#126]
Hi, I've just been having a look at your course, and I think having a quiz to check for prerequisites is a fantastic idea. Just one issue - in the first Shell question, the correct answer (pwd) is in green text, the rest in black (I'm guessing that it's because it's the only valid Unix command, so the markdown interpreter highlights it as such). Kind of gives away the answer, so it would be ideal if there's some way of stopping that colouring. On a similar note, the same thing crops up in the first git question - 'install' is green, the others are black (although in that case it points to the wrong answer!).

I do get lots of people who've previously attended the Plotting and Programming in Python workshop asking me about more advanced training material, so I'm really looking forward to going through your course in more detail to see if it's something I can refer them to. Thanks very much.

**Comment by anenadic** [comment]
Thank you @marklcrowe - fixed via [ca82219](https://github.com/carpentries-incubator/python-intermediate-development/commit/ca8221901a6671492093ce26fdd87dc8e6f95a59).
