### ISSUE TITLE
Virtual Environments and Conda

### ISSUE THREAD

**Issue by smangham** [carpentries-incubator/python-intermediate-development#130]
A good number of learners are using Conda as their Python, and have expressed concern over using pip and virtualenvs.

As far as I know you can just do `python -m venv venv` as normal within conda and whilst you will technically be using a venv _within_ a conda env it doesn't actually matter. It's probably worth calling this out.

**Comment by RGBYCP** [comment]
I am one of the learners who usually uses conda. I went this way to create in a conda environment a new Python venv.  Now I am using the pip from the `venv` and not from the conda environment. A bit odd, but it works.
So far, I have seen only one drawback. I do the exercises with VScode and sometimes I it opens a new terminal in VScode switch back to the base conda environment and not keeping my new venv.

**Comment by anenadic** [comment]
We moved away from using conda in the material and it woul be a big over head to support it as well. I suggest we put this under Troubleshooting and instructors Notes to make people teaching it aware.

**Comment by smangham** [comment]
I'd probably keep it in the main text as a callout, as even if we don't recommend Conda a lot of people will still be using it.

**Comment by anenadic** [comment]
Callout is good as well @smangham

**Comment by anenadic** [comment]
Also see #346 - this may be helpful. Closing this issue.
