### ISSUE TITLE
Extra comma in one test datasets? 

### ISSUE THREAD

**Issue by RGBYCP** [carpentries-incubator/python-intermediate-development#132]
In [https://carpentries-incubator.github.io/python-intermediate-development/24-diagnosing-issues-improving-robustness/index.html](https://carpentries-incubator.github.io/python-intermediate-development/24-diagnosing-issues-improving-robustness/index.html)

there is 

```py
@pytest.mark.parametrize(
    "test, expected, expect_raises",
    [
        ... # other test cases here, with None for expect_raises
        (
            [[-1, 2, 3], [4, 5, 6], [7, 8, 9]],
            [[0, 0.67, 1], [0.67, 0.83, 1], [0.78, 0.89, 1]],
            ValueError,
        ),
        (
            [[1, 2, 3], [4, 5, 6], [7, 8, 9]],
            [[0.33, 0.67, 1], [0.67, 0.83, 1], [0.78, 0.89, 1]],
            None,
        ),
    ])
```

Why is there a comma after `None` and `ValueError`, please?
My test runs as well without a comma after the expect_raises entries.
Thank you for your explanation.

**Comment by RGBYCP** [comment]
I asked today in the course, the comma is not needed.

**Comment by anenadic** [comment]
The comma is not needed but also is not a syntax error.

**Comment by tobyhodges** [comment]
[This StackOverflow answer provides a good, brief explanation of why these trailing commas are allowed and why people might use them](https://stackoverflow.com/a/11597911).

**Comment by unode** [comment]
May be also useful to know that [black](https://black.readthedocs.io) can [insert commas](https://black.readthedocs.io/en/stable/the_black_code_style/current_style.html#trailing-commas) for most of the same reasons @tobyhodges mentioned.
While optional, they are widely used.
