### ISSUE TITLE
Episode 23 - build matrix failure with newer packages unsupported by older Python

### ISSUE THREAD

**Issue by steve-crouch** [carpentries-incubator/python-intermediate-development#136]
A CI build can fail when a used Python package no longer supports a particular version of Python indicated in a GA CI build matrix, e.g. numpy 1.23.1 is not supported for Python 3.7. As we have it, the materials instruct the learners to just install the latest version of packages, hence the situation.

**Comment by anenadic** [comment]
Put this in Troubleshooting and Instructor Notes?

**Comment by anenadic** [comment]
The same/similar issue as #124.
