### ISSUE TITLE
Episode 33 - introduce `unittest.TestCase` before referencing it

### ISSUE THREAD

**Issue by anenadic** [carpentries-incubator/python-intermediate-development#139]
From @smangham  https://carpentries-incubator.github.io/python-intermediate-development/33-functional/index.html The 'testing impure functions' bit referrs to the `unittest.TestCase` class, but we don't introduce it earlier - do we just stick it in a file and run it like you would the normal pytest stuff?

**Comment by jag1g13** [comment]
Hi Aleks, this is a duplicate of #137 

I don't think we necessarily need to introduce `unittest`, we can just switch it to a pytest style since that's what we're using elsewhere. I suspect I wrote this example relatively early on when I was much more familiar with `unittest` than with `pytest`
