### ISSUE TITLE
Slightly inadequate explanation of conda in the lesson on virtual environments

### ISSUE THREAD

**Issue by krishnakumarg1984** [carpentries-incubator/python-intermediate-development#144]
In the [lesson introducing virtual environments](https://carpentries-incubator.github.io/python-intermediate-development/12-virtual-environments/index.html), it says:

> - `conda` which comes together with the Anaconda Python distribution.

The above statement + the subsequent text in the boxed tip also doesn't adequately cover that _`conda` is available **separately** from the Anaconda distribution, e.g. from `miniconda`, `mambaforge` or `miniforge`._

**Comment by anenadic** [comment]
Addressed in the AZ version of the course - to be merged here.

**Comment by anenadic** [comment]
Fixed via https://github.com/carpentries-incubator/python-intermediate-development/commit/67840a3415fdaab1d719e4c409dbffe259b9e315
