### ISSUE TITLE
Text correction: pycharm is not open-source

### ISSUE THREAD

**Issue by krishnakumarg1984** [carpentries-incubator/python-intermediate-development#146]
>in this course we will learn how to use [PyCharm](https://www.jetbrains.com/pycharm/), a free, open source Python IDE.

Pycharm is not directly open source. The underlying IntelliJ platform perhaps is, but cannot directly build pycharm from source.

It is a bit of a letdown to advocate a freemium product for open science (especially considering that SSI typically champions accessible FLOSS software).

**Comment by anenadic** [comment]
Jetbrains claims (last checked on  21 July 2022) at https://www.jetbrains.com/help/pycharm/installation-guide.html#:~:text=PyCharm%20is%20available%20in%20three,but%20they%20have%20fewer%20features.
> PyCharm is available in three editions: Professional, Community, and Edu. The Community and Edu editions are open-source projects and they are free, but they have fewer features. PyCharm Edu provides courses and helps you learn programming with Python. The Professional edition is commercial, and provides an outstanding set of tools and features. For details, see the [editions comparison matrix](https://www.jetbrains.com/pycharm/features/editions_comparison_matrix.html).

**Comment by anenadic** [comment]
The course mentions alternative IDEs too - in fact, it was taught to people using VS Code. The aim of the course is not to teach or promote a particular IDE - it is used as a vehicle to illustrate certain functionalities and different aspects of a software development process.
