### ISSUE TITLE
STFC pilot

### ISSUE THREAD

**Issue by elichad** [carpentries-incubator/python-intermediate-development#152]
We plan to run this course at STFC soon, in an instructor-led format on 5 half days across 2 weeks (1-2 and 7-9 November).

I won't be present when the course is run, so tagging the rest of the organisers and instructors who'll be able to provide feedback:
* @kpidge
* @jamesacris
* @patrick-austin
* @Monarda
* @mathewcsims

**Comment by anenadic** [comment]
Thank you for letting us know @elichad.

**Comment by anenadic** [comment]
Any chance you can give us the number of attendees for this workshop please @elichad? Many thanks!

**Comment by elichad** [comment]
I don't remember precisely and no longer have access, but I believe it was 36-39 people, with about half online and half in-person.

**Comment by patrick-austin** [comment]
That's accurate for the number of people signing up (36 according to my records) and the split, but on the first day we only had 27 attendess turn up on the first day, and a few less throughout the remaining 4 half days we had scheduled. Don't know if in person vs remote attendees were more or less likely to not attend after signing up.

**Comment by anenadic** [comment]
Thank you very much for the quick response @elichad - 27 showing up ion day 1 is a great number!
