### ISSUE TITLE
Setup - broken link to 'common issues'

### ISSUE THREAD

**Issue by kpidge** [carpentries-incubator/python-intermediate-development#154]
The link to 'common issues', found on the '[Setup](https://carpentries-incubator.github.io/python-intermediate-development/setup.html)' page (in the 'Common Issues & Tips' callout), is broken (returns a 404).

I would imagine that the link should point to the '[Common Issues, Fixes & Tips](https://carpentries-incubator.github.io/python-intermediate-development/common-issues/index.html)' page.

**Comment by anenadic** [comment]
Thank you for spotting this @kpidge - all the links have now been check and fixed.
