### ISSUE TITLE
Lesson pilot at Netherlands eScience Center 21st and 22nd of March

### ISSUE THREAD

**Issue by svenvanderburg** [carpentries-incubator/python-intermediate-development#159]
We will be teaching this workshop 21st and 22nd of March at the [Netherlands eScience Center](https://www.esciencecenter.nl/). And we are very excited about that, we feel a lot of researchers need and want to learn about this!
<details>
<summary><strong>Instructions</strong></summary>

Thanks for piloting the lesson! :heart:

Please let us know about your plan and dates for the pilot workshop.

If you want to provide us feedback after your pilot, you can use this issue to provide more details, e.g. on the following topics:

- Technical Issues
- Bugs & Unexpected Behaviour
- Missing Solutions
- Questions Asked by Learners
- Sources of Confusion
- Other notes
- Learner Feedback

</details>

**Comment by anenadic** [comment]
Fantastic news - thank you for letting us know @svenvanderburg. Let us know if you have any questions.

**Comment by svenvanderburg** [comment]
@anenadic its mentioned in the instructor notes that you might have introductory slides that we can use? If you have them, could you share them with s.vanderburg@esciencecenter.nl?

**Comment by anenadic** [comment]
> @anenadic @sstevens2 its mentioned in the instructor notes that you might have introductory slides that we can use? If you have them, could you share them with [s.vanderburg@esciencecenter.nl](mailto:s.vanderburg@esciencecenter.nl)?

Done @svenvanderburg

**Comment by svenvanderburg** [comment]
@anenadic here is our feedback for the course:

## How we run it
We ran the workshop on 2 consecutive days in person with 24 participants. We had 6 groups of 4 people and a team of 4 instructors. We knew we wouldn't be able to cover everything so we decided up front to skip parts of section 3 and section 5.

## What went well:
* The workshop registration was sold out in 40 minutes. 🎉 (normally we don't sell out or it takes a couple of days). This indicates that the topics covered is what researchers are anxiously waiting for to learn.
* The feedback from the participants was unanimously extremely positive.
* The course material is amazing. We did not encounter any problems.
* Having participants working on the material in groups and us walking around to answer (and ask!) questions worked out really well! After 3 years of live coding this was very refreshing. I feel like we covered a lot more material than with live coding.

## What can be improved:
* Because everyone moved at their own speed, it was difficult to keep everyone in sync. Especially since we had to do everything on 2 consecutive days. What would really help is to have an optional part at the end of each section, so fast learners can work on this while the others catch up.
* Quite some participants complained about the large pieces of text, especially in section 4. We decided that when we do the course the next time we will do some more theoretical parts more classically using slides so that there is a bit more variety in the modality of learning. Some suggestions for the lesson material:
   - Wherever possible it would be nice to use less text and make things more visual. 
   - Perhaps some of the larger blocks of text can be put in infoboxes so that it is more a 'further reading', so the main flow of the material is a bit less verbose.
* Next time we will teach it in 3 days. (but this is a critique on our way of running things, not the material)

## Final verdict
Overal we are super grateful for your contributions to this material. It is an amazing resource! 🙏 🙏 
We will teach it again next week, although with a heavily pruned fork (see https://esciencecenter-digital-skills.github.io/python-intermediate-development-uva/). And teach it in a 3-day workshop in December.

**Comment by anenadic** [comment]
@svenvanderburg's additional material: https://github.com/carpentries-incubator/python-intermediate-development/issues/204 - thank you
