### ISSUE TITLE
Example per-project library collections

### ISSUE THREAD

**Issue by sstevens2** [carpentries-incubator/python-intermediate-development#162]
This may not be needed but I could use an example to go with this sentence because I couldn't think of one on my own.

"Even languages that don’t explicitly have virtual environments have other mechanisms that promote per-project library collections." in [section 1 - virtual environments episode](https://carpentries-incubator.github.io/python-intermediate-development/12-virtual-environments/index.html)

**Comment by sstevens2** [comment]
sorry this is labeled with pilot label.  I did not read the issue options well

**Comment by anenadic** [comment]
That's a good point - one example could be [Maven](https://maven.apache.org/what-is-maven.html) (used primarily for Java projects). @steve-crouch what other examples could we include?

**Comment by bielsnohr** [comment]
Off the top of my head, some other examples are:

- Bundler for Ruby
- Conan can do per-project environments for C++
- Spack is a more generic tool that also has something resembling virtual environments
- Docker could be considered the "nuclear option": I want to bundle my _entire_ environment to distribute the application/software I am developing
  - the scope is much bigger for Docker, but the principle is the same

**Comment by anenadic** [comment]
Fixed via #336
