### ISSUE TITLE
explain -m flag

### ISSUE THREAD

**Issue by sstevens2** [carpentries-incubator/python-intermediate-development#163]
Maybe we should add a callout that explains the `-m` flag in the `python -m venv venv` command in the [section 1 virtual environments episode](https://carpentries-incubator.github.io/python-intermediate-development/12-virtual-environments/index.html)? - answer running the venv module as a script

**Comment by smangham** [comment]
Yeah, as it stands `-m` is kind of magic. It's probably not worth going into _too_ much detail, but a brief explanation would be good.

**Comment by smangham** [comment]
I'm going to have to untag myself as I'm currently _very_ overworked, apologies. Will email Aleks about the situation later.
