### ISSUE TITLE
Isn't inflammation a package?

### ISSUE THREAD

**Issue by sstevens2** [carpentries-incubator/python-intermediate-development#171]
My understanding is that a module is a `.py` file where a package is a collection of `.py` files connected with a `__init__.py`.

If so, we should maybe call `inflammation` consistently a package vs a module.  It is currently called a module in the [sec 1 linting episode](https://carpentries-incubator.github.io/python-intermediate-development/16-verifying-code-style-linters/index.html).

**Comment by sstevens2** [comment]
Specifically just under the code small callout box.

**Comment by smangham** [comment]
Closing this as the PR is now the thing that needs resolving.
