### ISSUE TITLE
Windows difference in activation

### ISSUE THREAD

**Issue by sstevens2** [carpentries-incubator/python-intermediate-development#174]
To activate venv for project, they need to use Scripts instead of bin

**Comment by anenadic** [comment]
There is a note that Windows users need to use "Scripts" folder (bin for Mac and Linux users).

<img width="1265" alt="image" src="https://user-images.githubusercontent.com/631719/224759576-d48a5282-d633-44c0-84e7-ab749819ff17.png">

But maybe there should be a reminder when we activate the environment.

**Comment by sstevens2** [comment]
That is what I was thinking too @anenadic, put in a draft of that change in the #176 PR.
