### ISSUE TITLE
Windows: venv, WSL, and Pycharm gives problems

### ISSUE THREAD

**Issue by svenvanderburg** [carpentries-incubator/python-intermediate-development#191]
When running Pycharm **Community edition** on Windows, one cannot configure Pycharm to use a venv environment created in WSL. I suggest to add a section in the lesson material’s trouble shooting about it. The problem is that WSL is not supported in the Community Edition of Pycharm.

There are a few options to solve it:
* Use vscode. It has much better WSL integration. Some participants in our course did this and had no trouble finding their way using the course material. 
* Use Pycharm professional edition (there’s a 30-day free trial). Then follow: https://www.jetbrains.com/help/pycharm/using-wsl-as-a-remote-interpreter.html#configure-wsl 
* Do everything 'locally' on Windows using git bash instead of using WSL.

**Comment by anenadic** [comment]
We recommend using Git Bash for the course - I will add an extra note int he setup to avoid WSL.

**Comment by anenadic** [comment]
Fixed via 490f19a.

**Comment by svenvanderburg** [comment]
Great! Thanks 🙏
