### ISSUE TITLE
Run of previous version of course at UKAEA on April 2023

### ISSUE THREAD

**Issue by bielsnohr** [carpentries-incubator/python-intermediate-development#197]
Workshop dates: run over 5 afternoon sessions, 11, 12, 18, 19, 25 April 2023

TODO fill in some of the details below

- Technical Issues
- Bugs & Unexpected Behaviour
- Missing Solutions
- Questions Asked by Learners
- Sources of Confusion
- Other notes
- Learner Feedback

**Comment by anenadic** [comment]
Any chance you can give us the number of attendees for this workshop please @bielsnohr ? Many thanks!

**Comment by bielsnohr** [comment]
Sorry for the delay (hoping this wasn't needed for the midterm review :grimacing: ) This was delivered to 15 people. I'll fill out some further details when I have a chance.
