### ISSUE TITLE
Reconcile existing slides for instructor-led delivery

### ISSUE THREAD

**Issue by bielsnohr** [carpentries-incubator/python-intermediate-development#200]
Myself @bielsnohr and @douglowe  have trialled doing a more "instructor-led" version of the course using some slides to guide this delivery. It was agreed that it would be good to get a base set of slides into the course repo for others to use and work off of.

My slides can be found here: https://github.com/ukaea-rse-training/python-intermediate-development/tree/gh-pages/slides

- [x] @bielsnohr  Create a html and pdf version of those for easier sharing
- [x] @douglowe please share a link to your slides
- [ ] Use sprint to try and reconcile these two into something for our course?

**Comment by bielsnohr** [comment]
Attaching the html and pdf versions of my slides for each section. Note, these are for the previous 4 section version of the course, and I am currently in the process of updating them for the present version of the course. Also note that these versions don't include the presenter notes.

[mbluteau_intermediate_rsd_slides_html.zip](https://github.com/carpentries-incubator/python-intermediate-development/files/11747749/mbluteau_intermediate_rsd_slides_html.zip)

[section_1_setting_up_environment.slides.pdf](https://github.com/carpentries-incubator/python-intermediate-development/files/11747817/section_1_setting_up_environment.slides.pdf)
[section_2_ensuring_correctness.slides.pdf](https://github.com/carpentries-incubator/python-intermediate-development/files/11747818/section_2_ensuring_correctness.slides.pdf)
[section_3_software_arch_design.slides.pdf](https://github.com/carpentries-incubator/python-intermediate-development/files/11747820/section_3_software_arch_design.slides.pdf)
[section_4_managing_software.slides.pdf](https://github.com/carpentries-incubator/python-intermediate-development/files/11747821/section_4_managing_software.slides.pdf)

**Comment by douglowe** [comment]
My slides are in google view format:

- [Intro](https://docs.google.com/presentation/d/1Tku422Kwi3W-rLBV9lHnMFD72hZWB7ThGQ0xqEwDZYY/edit?usp=sharing)
- [Section 1](https://docs.google.com/presentation/d/1RqYfCrN9eTMUd2dMzyrUXBuPlViTqSvOWU-UzaYIzvw/edit?usp=sharing)
- [Section 2](https://docs.google.com/presentation/d/1LlE0Gey-U6-4IUKGxG5B7XBVvY59dLvnGlVCF6UmkGc/edit?usp=sharing)
- [Section 3.1](https://docs.google.com/presentation/d/1j4-2gj7SEMeJymghsh7YjOiJwljuigbvYc9NBAOF7Po/edit?usp=sharing)
- [Section 3.2-5](https://docs.google.com/presentation/d/1YDlZ8i_9ZeO1MtcQhx5UwBw45k0nMwUhngl5-v5garc/edit?usp=sharing)
- [Section 4.1](https://docs.google.com/presentation/d/1fd7YtfIGtdYQELYulhvNvyjF1XyglMDPLS5T3Qb-6a0/edit?usp=sharing)
- [Section 4.2-3](https://docs.google.com/presentation/d/1HoROmFVnycdl_BlYt_Yx-HFtlUtzvalU3uhsd6v9p4o/edit?usp=sharing)
- [Section 5.1](https://docs.google.com/presentation/d/1naUtBQ4wbN-0MISIE4_0AenL2h-juigMvgRRikNm_xo/edit?usp=sharing)
- [Section 5.2-3](https://docs.google.com/presentation/d/1b8CIF7EU1bRWPuU3CRZf4bKRP41s-R8S1iEopAHaYs0/edit?usp=sharing)

**Comment by douglowe** [comment]
Could we hold the sprint to reconcile these around August? We should have heard about our funding bid by then - and if we get it I should be able to get more resource to work on this.
