### ISSUE TITLE
Additional section on continuous integration/continuous deployment?

### ISSUE THREAD

**Issue by svenvanderburg** [carpentries-incubator/python-intermediate-development#204]
Hey,

We recently taught a workshop using this material see https://github.com/carpentries-incubator/python-intermediate-development/issues/159 . We organized an additional morning on continuous integration/continuous deployment. We added the section to the material in our fork, you can check it out here: https://esciencecenter-digital-skills.github.io/python-intermediate-development-uva/60-section6-intro/index.html . It is focused on bitbucket, but could be adapted to GitHub easily I think.

Teaching with this material went very wel. We had an audience that could use this in practice, the participants actually maintained applications that were running in production, so not your typical researcher. Perhaps this could be added as an optional section?

Anyway, in case you had plans for something like this, or perhaps as source of inspiration, I am sharing :) I really love the material! ❤️

**Comment by svenvanderburg** [comment]
Hi @anenadic I will work on it, expect something this or next week.

**Comment by anenadic** [comment]
Thank you very much @svenvanderburg !

**Comment by svenvanderburg** [comment]
@anenadic would you or anyone else be able to review this?

**Comment by anenadic** [comment]
Hi, we are swamped at the moment but will try and got to it soon. Apologies for the delay!

**Comment by svenvanderburg** [comment]
No worries, take your time :)

**Comment by anenadic** [comment]
CD is a bit out of scope, it would add new material making the course even longer and hard to teach/test as we'd need a deployment infrastructure for this. Perhaps this could be a separate small tutorial?
