### ISSUE TITLE
Merged or incomplete sentence(s) in 42-software-reuse

### ISSUE THREAD

**Issue by tobyhodges** [carpentries-incubator/python-intermediate-development#205]
While working through #201, I came across these sentences in `42-software-reuse` (emphasis added by me to highlight the part that does not seem right):

> Reproducibility is required if we are to successfully claim that what we are doing when we write software fits within acceptable scientific practice, but it is also crucial that we can write software that can be understood by others. If others are unable to verify that a piece of software follows published algorithms **and ideally modified**. Where ‘others’, of course, can include a future version of ourselves.

I think perhaps two sentences got chopped and remixed at some point?

**Comment by steve-crouch** [comment]
Yes, I think you're spot on - I believe it should read:

> Reproducibility is required if we are to successfully claim that what we are doing when we write software fits within acceptable scientific practice, **it is also crucial that we can write software that can be understood and ideally modified by others. If others are unable to verify that a piece of software follows published algorithms, how can they be certain it is producing correct results?** Where ‘others’, of course, can include a future version of ourselves.
