### ISSUE TITLE
Replace use of git checkout command with git switch or git restore

### ISSUE THREAD

**Issue by bielsnohr** [carpentries-incubator/python-intermediate-development#208]
`git checkout` is a generally confusing command because it has so many use cases. Some sources I have read recommend replacing it with either `git switch` or `git restore` depending on the use case. See https://stackoverflow.com/a/57266005

I  suggest that we replace all occurrences of `git checkout` with the appropriate version of `git switch` or `git restore`. It is worth noting that `git` itself no longer recommends using `git checkout` if you want to discard changes in the working tree, and instead suggests `git restore`. 

I am happy to raise a PR is we get consensus on this.

**Comment by douglowe** [comment]
This sounds very sensible to me.

**Comment by anenadic** [comment]
Sounds good - a PR would be welcome @bielsnohr
