### ISSUE TITLE
Lesson pilot at Plasma Science and Fusion Centre

### ISSUE THREAD

**Issue by RemDelaporteMathurin** [carpentries-incubator/python-intermediate-development#233]
<details>
<summary><strong>Instructions</strong></summary>

Thanks for piloting the lesson! :heart:

Please let us know about your plan and dates for the pilot workshop.

If you want to provide us feedback after your pilot, you can use this issue to provide more details, e.g. on the following topics:

- Technical Issues
- Bugs & Unexpected Behaviour
- Missing Solutions
- Questions Asked by Learners
- Sources of Confusion
- Other notes
- Learner Feedback

</details>

We expect around 20 people and teach this workshop over the course of two days.
@eepeterson

**Comment by anenadic** [comment]
Thank you very much @RemDelaporteMathurin. What dates have you got in mind? We are also currently making some changes to the code review and/or software architecture episodes - if you'd like to try the new version (provided we merge before your workshop) and give us some feedback that'd be very much appreciated. If not - make sure you fork the course as it is now.

**Comment by RemDelaporteMathurin** [comment]
The course will be held on the 20th and 21st of September.

**Comment by RemDelaporteMathurin** [comment]
@anenadic do you know when the new version will be merged?

**Comment by anenadic** [comment]
Not sure @RemDelaporteMathurin - we will try to do a push to review and merge this or next week if at all possible.

**Comment by anenadic** [comment]
An update on the merge of #226 @RemDelaporteMathurin - the PR requires a bit more work and we are all going to be extremely busy in September so no guarantee that the changes will be tested and merged and the episode will likely remain as is.

**Comment by anenadic** [comment]
> **Instructions**
> Thanks for piloting the lesson! ❤️
> 
> Please let us know about your plan and dates for the pilot workshop.
> 
> If you want to provide us feedback after your pilot, you can use this issue to provide more details, e.g. on the following topics:
> 
> * Technical Issues
> * Bugs & Unexpected Behaviour
> * Missing Solutions
> * Questions Asked by Learners
> * Sources of Confusion
> * Other notes
> * Learner Feedback
> 
> We expect around 20 people and teach this workshop over the course of two days. @eepeterson

@RemDelaporteMathurin Are going to run this workshop in instructor-led mode (where an instructor teaches it to the cohort) or guided self-learning (where learners go through the material themselves and can get help from helpers)?

**Comment by RemDelaporteMathurin** [comment]
@anenadic it is going to be instructor-led

**Comment by anenadic** [comment]
Any feedback on how the workshop went @RemDelaporteMathurin ?

**Comment by anenadic** [comment]
Is there any feedback to report to us @RemDelaporteMathurin? How many people did you have in the end? How did the workshop go?

**Comment by RemDelaporteMathurin** [comment]
@anenadic sorry about the late reply

We had about 20 people attending.
The workshop went well, we adapted it a bit because we ran it over two days (8am to 3pm) and day 2 was an application of the things we learned on day 1 (a hackaton of some sort) where attendees would try to collaborate on a common project (https://github.com/j-fletcher/fusion-toolbox) and implement some features.

Day 1 obviously did not cover 100% of the materials in the workshop. We spent most of the time on sections 1 and 2 then briefly went through section 3.

Some parts of section 3 weren't of much interest to us and felt more like python tricks than tools for development at scale.

We ran the workshop on VSCode and not pycharm. We felt like this should be the default of the workshop as VSCode is by far the most popular IDE out there.

@eepeterson feel free to add anything

**Comment by anenadic** [comment]
> @anenadic sorry about the late reply
> 
No worries - thanks for taking the time to give us feedback @RemDelaporteMathurin .

> We had about 20 people attending. The workshop went well, we adapted it a bit because we ran it over two days (8am to 3pm) and day 2 was an application of the things we learned on day 1 (a hackaton of some sort) where attendees would try to collaborate on a common project (https://github.com/j-fletcher/fusion-toolbox) and implement some features.
> 
That sounds interesting - we always wish to apply the things people learn on their own projects but somehow are never 100% successful in implementing this due to the lack of time.

> Day 1 obviously did not cover 100% of the materials in the workshop. We spent most of the time on sections 1 and 2 then briefly went through section 3.
> 
> Some parts of section 3 weren't of much interest to us and felt more like python tricks than tools for development at scale.
We are working on updating section 3 to make it less theoretical and hopefully more useful to people. 

> 
> We ran the workshop on VSCode and not pycharm. We felt like this should be the default of the workshop as VSCode is by far the most popular IDE out there.
We did a check of the proportions of community using PyCharm and VSCode and there seemed to be equal split. But in the most recent workshops we noticed a definite lean towards VSCode. We have an "extras" episode on VSCode and are now thinking of changing the course to incorporate this in the main material.  While this is not a difficult change, there is a lot of manual work required to change all the screenshots - we would welcome any effort in this direction if anyone from your team is willing to give it a go. 

Many thanks for your feedback - hope you continue to use the course.
