### ISSUE TITLE
Check the episodes with screenshots of PyCharm, GitHub Milestones and projects and check they are up-to-date

### ISSUE THREAD

**Issue by anenadic** [carpentries-incubator/python-intermediate-development#237]

**Comment by svenvanderburg** [comment]
From our workshop 11-12-13 december: the screenshots for PyCharm are not up-to-date. But I guess you don't want to update these because of #262

**Comment by anenadic** [comment]
@svenvanderburg we did redo the PyCharm screenshots as we are not sure yet when the switch to VSCode will happen - can you recall which screenshots were out of date?

**Comment by svenvanderburg** [comment]
No, @sjvrijn, @drcandacemakedamoore, or @f-hafner do you recall I think one of you mentioned this to me.

**Comment by anenadic** [comment]
Closed via #340
