### ISSUE TITLE
Poor flow of Git authentication and push section

### ISSUE THREAD

**Issue by bielsnohr** [carpentries-incubator/python-intermediate-development#243]
In section 1 episode 4, this section on authentication with Git doesn't read particularly well and seems incomplete:

![Screenshot from 2023-10-18 11-41-39](https://github.com/carpentries-incubator/python-intermediate-development/assets/6177028/ad4797d3-1f96-4f73-9768-e6c47d8552d3)

Also, there is no mention of how to set up SSH keys. GitHub has a pretty decent section on this that we should link to: https://docs.github.com/en/authentication/connecting-to-github-with-ssh/adding-a-new-ssh-key-to-your-github-account?tool=webui That documentation page is a bit tricky because it has different versions for Windows, Mac and Linux near the top (but switching between them is by no means obvious).

**Comment by bielsnohr** [comment]
Ah, this is me not reading closely enough. I see that we have now gone through SSH key generation and adding to GitHub, and that we recommend cloning exclusively through SSH.

Therefore, my only slight issue is the line that starts:

> So, when you run the command below:
> ```bash
> git push origin main
> ```
> .... [then goes immediately into a warning box]

It doesn't flow very well. I instead suggest:


> So, assuming you have an proper authentication method set up, you should be able to push your changes with the command:
> ```bash
> git push origin main
> ```
> .... [then go to the warning box]

**Comment by anenadic** [comment]
Suggestion sounds good to me - do you want to do a PR for this @bielsnohr? I am adding this issue to the list for the beta release.

**Comment by anenadic** [comment]
Fixed via #271 @bielsnohr - will ask you to review.
