### ISSUE TITLE
Another pilot at UKAEA in November 2023

### ISSUE THREAD

**Issue by bielsnohr** [carpentries-incubator/python-intermediate-development#247]
We will be running another iteration of the course starting on 2023-11-09, going for 6 afternoon sessions, finishing on 2023-11-24.

Post workshop, update with these points:

- Technical Issues
- Bugs & Unexpected Behaviour
- Missing Solutions
- Questions Asked by Learners
- Sources of Confusion
- Other notes
- Learner Feedback

**Comment by anenadic** [comment]
Can you report the number of learners please, if you recall, @bielsnohr?
