### ISSUE TITLE
All lessons - check code snippets

### ISSUE THREAD

**Issue by anenadic** [carpentries-incubator/python-intermediate-development#26]
Some code snippets use python3 and some python - depending on individual setups. E.g. Day 1 morning uses `pytnon` then Day 1 afternoon uses `python3`.

**Comment by steve-crouch** [comment]
Revisted: we should always use python3 in our material.

**Comment by anenadic** [comment]
https://carpentries.org/help-wanted-issues/ and use labels 'help wanted' and 'good first issues'.

**Comment by anenadic** [comment]
Standing issue - should be done periodically.
