### ISSUE TITLE
Use less text

### ISSUE THREAD

**Issue by svenvanderburg** [carpentries-incubator/python-intermediate-development#260]
When teaching (#159) quite some participants complained about the large pieces of text, especially in section 4. 

Wherever possible it would be nice to use less text and make things more visual.
Perhaps some of the larger blocks of text can be put in infoboxes so that it is more a 'further reading', so the main flow of the material is a bit less verbose.

**Comment by anenadic** [comment]
We understand the point, but the course is meant for self-learning, hence the need for quite detailed explanations so that people can follow on their own. Readability may be improved with the new Carpentries workbench, which has improved accessibility.
