### ISSUE TITLE
Improve links provided for setting up HTTPS authentication

### ISSUE THREAD

**Issue by bielsnohr** [carpentries-incubator/python-intermediate-development#265]
The links provided in [Episode 4, Section 1, "Collaborative Software Development Using Git and GitHub"](https://carpentries-incubator.github.io/python-intermediate-development/14-collaboration-using-git/index.html#checking-in-changes-to-our-project) for authentication with https in git for GitHub proved not to be that helpful for a few learners in our most recent run.

[Linking to the blog post about why GitHub is making this change](https://github.blog/2020-12-15-token-authentication-requirements-for-git-operations/) isn't particularly relevant and a bit of a distraction when someone is just trying to get things to work.

[The generation of the personal token is fine](https://docs.catalyst.zoho.com/en/tutorials/githubbot/java/generate-personal-access-token/), but then there are no instructions about how to actually use that token.

From my experience getting a few learners through this bit, the proper resource to use is the actual GitHub documentation: https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/managing-your-personal-access-tokens#creating-a-personal-access-token-classic

Ideally, I like to get learners using SSH keys, but in some cases HTTPS is needed.

**Comment by anenadic** [comment]
Is this issue also now fixed via #271 and can be closed @bielsnohr?
