### ISSUE TITLE
Consider finding someone to check and regenerate code output and images in material

### ISSUE THREAD

**Issue by steve-crouch** [carpentries-incubator/python-intermediate-development#29]
At some point we're going to have to go through the entire material and update all the images and code outputs, which will take a long time!

Consider finding someone who's keen to help out with lesson development to regenerate our tutorial material images and code outputs. List potential candidates here!

**Comment by steve-crouch** [comment]
Discussed again - suggest add as a checkout task for learners, i.e. nominate this repo to be included in the possible checkout tasks page

**Comment by anenadic** [comment]
https://carpentries.org/help-wanted-issues/ and use labels 'help wanted' and 'good first issues'.

**Comment by anenadic** [comment]
Fixed via 0d1dbf2c06f064214bfd7537ee18ea60c474c513, ec887f6b731d66aa5fa5678d8792e2af7f5b10b9, ec887f6b731d66aa5fa5678d8792e2af7f5b10b9 and ec887f6b731d66aa5fa5678d8792e2af7f5b10b9.
