### ISSUE TITLE
Updating explanation of Object Oriented Programming

### ISSUE THREAD

**Issue by carlosug** [carpentries-incubator/python-intermediate-development#295]
Great lessons! :heart:

<details>
<summary><strong>Improvement</strong></summary>

Perhaps modify this paragraph in  [https://carpentries-incubator.github.io/python-intermediate-development/33-programming-paradigms/index.html#object-oriented-programming](https://carpentries-incubator.github.io/python-intermediate-development/33-programming-paradigms/index.html#object-oriented-programming)

This lesson is heavily based on the inflammation example, instead chemistry research as shown _below_:

_For example, if we’re writing a simulation for our chemistry research, we’re probably going to need to represent atoms and molecules. Each of these has a set of properties which we need to know about in order for our code to perform the tasks we want - in this case, for example, we often need to know the mass and electric charge of each atom._ 

</details>

**Comment by anenadic** [comment]
Thakn you for your feedback - perhaps you'd like to suggest a wording? We use doctors and patients examples in the code; it's OK to have a variety of different examples.
