### ISSUE TITLE
Update the lesson to use the new lesson template

### ISSUE THREAD

**Issue by anenadic** [carpentries-incubator/python-intermediate-development#317]
The new lesson template - [The Carpentries Workbench](https://carpentries.github.io/sandpaper-docs/).
[Translation guide](https://carpentries.github.io/sandpaper-docs/migrating-from-styles.html) available.

*UPDATE:* For visibility, the lesson transition is being done in [the fork of @bielsnohr](https://github.com/bielsnohr/python-intermediate-development)

**Comment by anenadic** [comment]
An email from @tobyhodges from 2024-02-14 with subject "Re: Testing a Workbench Transition Workflow" containing instructions:

Hi Tim, hi everyone,

Thanks to everyone who has tried out the workflow so far and provided feedback. I have made some improvements to the documentation based on your comments, and the workflow is now provided as [a page on the main Workbench documentation lesson site](https://carpentries.github.io/sandpaper-docs/migrating-from-styles.html).

Feedback is still welcome: it can still be further improved. Now that the page is part of that larger documentation site, you can open issues and pull requests on [the source repository](https://github.com/carpentries/sandpaper-docs/).

Finally, to re-emphasise words of caution from the workflow documentation: please make a backup of your lesson and read all of the instructions carefully before running the commands to transition your lesson. 

Thanks,

Toby

**Comment by bielsnohr** [comment]
A partial sub-task of this is #370 which has the more limited scope of just trialling out the conversion in preparation for CarpentryConnect. I think it is still worthwhile to have both in existence, with this being the longer-term and overarching issue.

**Comment by bielsnohr** [comment]
This is my current list of things that have come up while doing the conversion. Some will probably need to be split into follow-up tasks:

- [ ] Move over to using Mermaid within the lesson once it is enabled in the workbench (link to
  current MR for that)
- [ ] Add alt-text to all images and consider captioning some of them. The caption is now in the
  place where the alt-text used to be, and the alt-text is in an extra attribute after the
  definition of the image (e.g. `[caption text](./path/to/image){alt='Alt text'}`)
- [ ] Consider creating learner profiles
- [ ] The "More" drop down to get to learner extras moves into the hamburger side menu *at the
  bottom* when the screen width is reduced beyond a certain limit. Doug and I felt this wasn't great
  UX and could possibly be improved.

**Comment by anenadic** [comment]
> This is my current list of things that have come up while doing the conversion. Some will probably need to be split into follow-up tasks:
> 
>     * [ ]  Move over to using Mermaid within the lesson once it is enabled in the workbench (link to
>       current MR for that)
Agree - this may not happen soon, but there is a custom version of sandpaper by Dimitros Theodorakis that supports Mermaid. Something to consider?
> 
>     * [ ]  Add alt-text to all images and consider captioning some of them. The caption is now in the
>       place where the alt-text used to be, and the alt-text is in an extra attribute after the
>       definition of the image (e.g. `[caption text](./path/to/image){alt='Alt text'}`)
> 
>     * [ ]  Consider creating learner profiles
> 
>     * [ ]  The "More" drop down to get to learner extras moves into the hamburger side menu _at the
>       bottom_ when the screen width is reduced beyond a certain limit. Doug and I felt this wasn't great
>       UX and could possibly be improved.

Sounds like a great list - I am going to create a separate issue and copy these over so we do not lose them in the guts of this issue. As already mentioned, these should be separate issues.

**Comment by bielsnohr** [comment]
Given separate issues have been created for follow up and notifying any users of the lesson, I think we can consider this closed! :partying_face:

**Comment by bielsnohr** [comment]
> Agree - this may not happen soon, but there is a custom version of sandpaper by Dimitros Theodorakis that supports Mermaid. Something to consider?

I did see that, and it would involve modifying the build infrastructure to point to that, which I don't immediately know how to do, and given my lack of R ecosystem experience, I am hesistant to head in that direction. It also means we might not get through automatic updates to sandpaper. So I think for the moment, we wait for Mermaid to come through on the core version. We don't have too many charts in it yet.

**Comment by tobyhodges** [comment]
You can pin sandpaper to a particular ref (branch, repo, even a commit) by adding a line at the end of your config.yaml:

```yaml
sandpaper: tobyhodges/sandpaper@some-branch
```

[See an example](https://github.com/carpentries/lesson-development-training/commit/fb28a3ec586b22945a0c4e2d05f3088ef0d3af0c) where I pinned varnish to a particular branch in my fork.

The downside to doing this of course is that you'll need to rely on Dimitrios keeping his Mermaid-enabled branch up-to-date with any changes that get made to sandpaper upstream.
