### ISSUE TITLE
Refactoring of section 3

### ISSUE THREAD

**Issue by steve-crouch** [carpentries-incubator/python-intermediate-development#321]
Taking into account PR #297, number of steps for refactoring:

1. Learning narrative changes - software design episode
    - move poor design choices and technical debt to after intro
    - make design goals understandability, testable, maintainable (as high-level concepts) then echo these high-level concepts throughout the intros to code refactoring and code abstractions
    - move architecture & MVC intro to after good software design goals, then include a discussion of how MVC relates to the high-level concetps of understandability, testability, maintainability
    - bringing software design episode techniques section up to level of design
 
2. Reordering of refactoring and abstraction episodes to follow better the narrative of design / abstraction / implementation (see PR #327)
    - exercises may need some work
    - highlight in episode introductions the high-level concepts

3. Update section intro to reflect the reordering and learning narrative changes

4. Verify changes w.r.t. Thomas' inflammation code repo updates

**Comment by anenadic** [comment]
Closed via #333
