### ISSUE TITLE
Rename virtual environment - use different name to “venv” since it can be confusing for learners

### ISSUE THREAD

**Issue by anenadic** [carpentries-incubator/python-intermediate-development#328]
We could have “venv*” in gitignore and “venv_xyz” as the name of the venv. Despite the convention, we should go with clarity for learners.

**Comment by bielsnohr** [comment]
Was there specific feedback that `venv` is a confusing name? I don't think adding something at the end will necessarily make it that much clearer. I could see `virtual-env` being perhaps slightly more clear; however, as you mention this goes against the established convention, and I think that is a fine line to balance. Further discussion in upcoming meeting that I will add here once we have it.

**Comment by anenadic** [comment]
Yes, there was a specific feedback that it was confusing throughout the last workshop in March 2024. I was thinking of changing the whole material, not just adding a note at the end. Even though it may not be conventional (i.e. the convention being to use names such as "vnev" or ".venv") - Greg Wilson always said "never be scared to sacrifice truth for clarity", in this case "convention over clarity".

**Comment by anenadic** [comment]
Discussions at the maintainers call on 2024-05-08:
Renaming the venv directory storing the virtual environment to something more meaningful for users but deviating from the convention. How far do you go with breaking the convertion to make it easier for people? Are we seeing this repeatedly in multiple workshops? Do we want to make changes based on just one workshop? Do we need more evidence to make this kind of change? Put this in instructor notes as a course of confusion? Clarification at the start, making it more clear in the rest of the material? 

Conclusion: stay with the convention for the time being but leave it as an open issue. Ask Sven to pay attention to this next time they run the course. Add a reminder to activate a virtual environment ?
