### ISSUE TITLE
Lesson development @ Netherlands eScience Center

### ISSUE THREAD

**Issue by svenvanderburg** [carpentries-incubator/python-intermediate-development#343]
@anenadic, @bielsnohr, @steve-crouch We (me and some colleagues from the Netherlands eScience Center) are planning to add some improvements to this lesson in a lesson development sprint day at the 14th of May. The improvements will be based on our teachings. We will for example pick up #258, but expect a few more issues in the next weeks.

It is a bit of a selfish action actually since we want these things to be in the material when we teach it next time. But we are super open to any form of collaboration, the worst case scenario for us would be if we have to make these improvements to our own fork that will start to deviate from this lesson. 

So some ideas/questions:
- Maybe you could join our sprint? (No is an answer)
- Are there any parts that we should not touch, because of possible conflicts? I see that there are PRs open with quite some commits.
- Any issues that you would like us to pick up? (For example we have quite some experience by now with #317 so we could pick that up, especially since we keep getting this feedback: #260)

Let me know your thoughts!

**Comment by anenadic** [comment]
Hi @svenvanderburg,

Thank you for the planned contributions and sprint. If you email the group at python-inter-inflammation@ lists.carpentries.org with the calendar invite - perhaps someone from the maintainers team will be able to join (but no promises).

Contributing guidelines are at: https://github.com/carpentries-incubator/python-intermediate-development/blob/gh-pages/CONTRIBUTING.md. At this point, we are not encouraging big additions to the material - if you can, focus on fixing the issues for the April sprint: https://github.com/carpentries-incubator/python-intermediate-development/milestone/5.

We are keeping #317 for a workshop in CarpentryConnect Heidelberg to use it as an example, but if you want to work on it feel free to tackle it.

Issue #260 - at this point we'd discourage big changes to the material but more diagrams and visuals are more than welcome.

**Comment by svenvanderburg** [comment]
Hi @anenadic,

I invited the email group. Would indeed be cool if any of you can join, but we're aware that it is on a short notice.

We won't work on any big differences, promise :) And use the milestone as a guidance for issues with priority.

I will very likely also be in Heidelberg, so I hope to meet you then!
