### ISSUE TITLE
setup: check that ssh to github works

### ISSUE THREAD

**Issue by f-hafner** [carpentries-incubator/python-intermediate-development#347]
In our last workshop at the escience center, I noticed a few people having problems with the ssh authentication on github. I think it would be nice to have people check before the workshop that they can actually authenticate with ssh on github. Ie, after the line "“Add SSH key” button." in the [setup instructions](https://carpentries-incubator.github.io/python-intermediate-development/setup.html), add something like this:

Now, we can check that the ssh connection is working:
```bash
ssh -T git@github.com
```

**Comment by svenvanderburg** [comment]
Fixed with #354 @anenadic or @f-hafner can you close it?
