### ISSUE TITLE
Wrap-up: Add conceptual framework diagram of how pieces of technology fit together

### ISSUE THREAD

**Issue by anenadic** [carpentries-incubator/python-intermediate-development#35]
As a first thing in the intro episode and potentially in a intro to the whole workshop if we do it

**Comment by steve-crouch** [comment]
Amended to be about what's in the wrap-up as opposed to intro.

**Comment by anenadic** [comment]
There is a concept map added to this episode already - perhaps turn this into a reflection exercise and use the concept map as one suggested solution.
