### ISSUE TITLE
test-suite branch created but never switched to

### ISSUE THREAD

**Issue by sjvrijn** [carpentries-incubator/python-intermediate-development#364]
In episode 2.1, the `test-suite` branch is created using `git branch -c test-suite`, but is not followed by an explicit `git switch test-suite` command. If participants follow the instructions to the letter, this means that they are performing all their commits on the `develop` branch instead. At the end of the lesson, no switch instructions are given before `git push origin test-suite`, which then contains no new commits.

Is this supposed to be `git switch -c test-suite` instead?

**Comment by anenadic** [comment]
Hi, yes it is - thank you for spotting this @sjvrijn. Any chance you can do a PR please?
