### ISSUE TITLE
Trial out the conversion to the Workbench framework

### ISSUE THREAD

**Issue by bielsnohr** [carpentries-incubator/python-intermediate-development#370]
As part of the maintainers' meeting on 2024-07-31, it was agreed that it would be good to test out the conversion to the Carpentries' Workbench in advance of the mini-hackathon at CarpentryConnect2024. We don't necessarily need to perform the entire conversion, but we should have a good idea of what is involved and the breakdown of tasks.

Currently, this is scheduled for next maintainers' meeting on 2024-08-28.

**Comment by bielsnohr** [comment]
See #317 for instructions about how to do the conversion.

**Comment by anenadic** [comment]
Aleks's translation notes: https://codimd.carpentries.org/old-lesson-format-translation-workflow?both
Matt's translation notes: https://codimd.carpentries.org/carpentries-workbench-steps-mbluteau?edit=
