### ISSUE TITLE
Use Markdown syntax for images throughout to better control the outlook of diagrams

### ISSUE THREAD

**Issue by anenadic** [carpentries-incubator/python-intermediate-development#40]

**Comment by steve-crouch** [comment]
Perhaps one to consider post-incubator; can be done in markdown.

**Comment by anenadic** [comment]
The way to do it fully in Markdown now is to use the following syntax, e.g.:
![pic alt](../fig/pic.png){: .image-with-shadow width="800px" }

**Comment by anenadic** [comment]
May require lesson template update.
