### ISSUE TITLE
Add instructor notes

### ISSUE THREAD

**Issue by anenadic** [carpentries-incubator/python-intermediate-development#74]
For other instructors to deliver the material.

**Comment by steve-crouch** [comment]
From discussion on 07/09/2021, e.g.

- Learner environment (the easiest way to do that, link to set up section, reasons why it's like that)
- Workshop operations (infrastructure, arrangement of virtual telecon rooms/config, etc.)
- Higher requirement of instructors compared to novice material - probably broad questions
- Audience-level gap between attending standard SWC, then straight to this without practice/consolidation - need to get that balance right (know your audience, prior knowledge)
- Any guidance for specific exercises, particularly Day 4 (the uniqueness of that day's activities)

**Comment by anenadic** [comment]
Issues with GitHub and first time participants do push - they may be asked for 2FA (if they have configured it) or for the access token (to push over HTTPS).

**Comment by anenadic** [comment]
Could add a FAQ - list of questions people are expected to ask - as a separate page and link from Instructor Notes too.

**Comment by anenadic** [comment]
Fixed via #4d305c8fb5172b2cf58f047a488069fd9a005481.
