### ISSUE TITLE
Issues with 04-ides.md

### ISSUE THREAD

**Issue by gpfrancis** [carpentries-incubator/python-intermediate-development#89]
Working through the section on IDEs I found the following issues (using a clean installation of PyCharm 2021.2.3 on macOS with Python 3.10).

1. Code completion did not work for me at the point where it is covered - only after the Python interpreter is configured.
2. The steps given to set the Python interpreter appear to produce the same result as accepting PyCharm's suggestion, but take a lot longer. While I can see the value of knowing where these settings are, this is very specific to PyCharm so this might be a place where time could be saved if necessary?
3. For the "Adding an External Library" section `argparse` is probably a poor choice since it is built-in (in recent Python versions). Pip will still install a copy in site-packages if requested, but this is not required and will not be included in the output of `pip freeze` (which means that the solution to the exercise is incorrect).

**Comment by anenadic** [comment]
Any alternative suggestions for 3. above @gpfrancis? The example is a bit contrived but we'd like to cover installing a library at this point. Unless we leave it for later when we install pytest?

**Comment by gpfrancis** [comment]
I'd have thought it depends what you want to do about point 2. If exploring the PyCharm interface is an important part of this lesson then maybe keep everything as is except install pytest now instead of argparse. It's slightly less contrived since at least we will need pytest - even if not until the following day - and it should be able to demonstate use of `pip freeze`, which doesn't work with argparse. Conversely, if this lesson is getting too long and in danger of overrunning (it was certainly one of the longer ones in terms of how long it took me to work through), then maybe just accept the default suggestion for the interpreter and put off the whole thing until the following day?

**Comment by anenadic** [comment]
OK, will have a look at this and discuss with @steve-crouch and @jag1g13 - thank you for looking into this @gpfrancis.

**Comment by anenadic** [comment]
Configuring Python interpreter in PyCharm is important as a concept so we might keep it. Or switch to a callout.

**Comment by anenadic** [comment]
We will switch from installing argparse to pytest in PyCharm to make sure we show both actions (setting up a virtual end and install an external package) in both tools (command line and PyCharm) to draw a parallel.

**Comment by anenadic** [comment]
Fixed via #94.
