### ISSUE TITLE
Pushing workflow to GitHub may require authorisation

### ISSUE THREAD

**Issue by gpfrancis** [carpentries-incubator/python-intermediate-development#90]
Towards the end of 15-continuous-integration-automated-testing.md we push our new CI workflow to GitHub. If the user is authenticated to GitHub using a personal access token (which is likely since this is recommended by GitHub) then this will be rejected unless the access token has the workflow scope granted. Fixing this isn't a big issue, but it might be helpful to have instructions available somewhere.

**Comment by anenadic** [comment]
We need this earlier in the material - the first time we do a push (in Git/GitHub episode). We need to explain what is happening, how to get an access token and put it locally.

**Comment by anenadic** [comment]
We already have 2FA and access tokens mentioned in episode 02-software-development when importing the template projects. We also need to make another note in the GitHub episode.

**Comment by anenadic** [comment]
Point them to documentation: https://github.blog/2020-12-15-token-authentication-requirements-for-git-operations/. Alos the personal access token needs to have "workflows" scope enabled for the token to be able to use GH Actions - so for existing tokens users may need to modify them.
