### ISSUE TITLE
README example not correctly parsed by GitHub

### ISSUE THREAD

**Issue by gpfrancis** [carpentries-incubator/python-intermediate-development#92]
32-preparing-software-reuse.md contains the following example on line 134:
```
![Continuous Integration build in GitHub Actions](https://github.com/<your_github_username>/python-intermediate-inflammation/workflows/CI/badge.svg?branch=main){: .image-with-shadow width="800px"}
```
However, the attribute list is not supported in GitHub flavor Markdown so it renders like this:

<img width="840" alt="Screenshot 2021-11-10 at 20 15 07" src="https://user-images.githubusercontent.com/30290454/141186819-6da7b341-2a96-4860-9d90-e91af5534707.png">

**Comment by anenadic** [comment]
I've removed the image attribute but this needs checking @steve-crouch.
