### ISSUE TITLE
Proofreading by the Comms team

### ISSUE THREAD

**Issue by anenadic** [carpentries-incubator/python-intermediate-development#93]
List of episodes:
- [x] [1. Setting the Scene For the Workshop](https://carpentries-incubator.github.io/python-intermediate-development/00-setting-the-scene/index.html)
- [x] [2. Section 1: Environment For Collaborative Code Development](https://carpentries-incubator.github.io/python-intermediate-development/01-section1-intro/index.html)
- [x] [3. Introduction to Software Design and Development](https://carpentries-incubator.github.io/python-intermediate-development//02-software-development/index.html)
- [x] [4. Virtual Environments For Software Development](https://carpentries-incubator.github.io/python-intermediate-development/03-virtual-environments/index.html)
- [x] [5. Integrated Software Development Environments](https://carpentries-incubator.github.io/python-intermediate-development/04-ides/index.html)
- [x] [6. Collaborative Software Development Using Git and GitHub](https://carpentries-incubator.github.io/python-intermediate-development/05-collaboration-using-git/index.html)
- [x] [7. Python Coding Conventions](https://carpentries-incubator.github.io/python-intermediate-development/06-coding-conventions/index.html)
- [x] [8. Section 2: Ensuring Correctness of Software at Scale](https://carpentries-incubator.github.io/python-intermediate-development/11-section2-intro/index.html)
- [x] [9. Automatically Testing your Software](https://carpentries-incubator.github.io/python-intermediate-development/12-automatically-testing-software/index.html)
- [x] [10. Scaling Up Unit Testing](https://carpentries-incubator.github.io/python-intermediate-development/13-scaling-up-unit-testing/index.html)
- [x] [11. Continuous Integration for Automated Testing](https://carpentries-incubator.github.io/python-intermediate-development/15-continuous-integration-automated-testing/index.html)
- [x] [12. Diagnosing Issues and Improving Robustness](https://carpentries-incubator.github.io/python-intermediate-development/16-diagnosing-issues-improving-robustness/index.html) 
- [x] [13. Section 3: Software Architecture and Design](https://carpentries-incubator.github.io/python-intermediate-development/21-section3-intro/index.html)
- [x] [14. Programming Paradigms](https://carpentries-incubator.github.io/python-intermediate-development/22-programming-paradigms/index.html)
- [x] [15. Object Oriented Programming](https://carpentries-incubator.github.io/python-intermediate-development/23-object-oriented/index.html) 
- [x] [16. Functional Programming | What is a function really?](https://carpentries-incubator.github.io/python-intermediate-development/24-functional/index.html)
- [x] [17. Software Design](https://carpentries-incubator.github.io/python-intermediate-development/25-software-design/index.html) 
- [x] [18. Persistence](https://carpentries-incubator.github.io/python-intermediate-development/26-persistence/index.html) 
- [x] [19. Section 4: Developing Software In a Team and Releasing It](https://carpentries-incubator.github.io/python-intermediate-development/31-section4-intro/index.html) 
- [x] [20. Preparing Software for Reuse](https://carpentries-incubator.github.io/python-intermediate-development/32-preparing-software-reuse/index.html)
- [x] [21. Assessing Software for Suitability and Improvement](https://carpentries-incubator.github.io/python-intermediate-development/34-assessing-software-suitability-improvement/index.html) 
- [x] [22. Software Improvement Through Feedback](https://carpentries-incubator.github.io/python-intermediate-development/35-improvement-through-feedback/index.html) 
- [x] [23. Wrap-up](https://carpentries-incubator.github.io/python-intermediate-development/40-wrap-up/index.html)

**Comment by JacalynLaird** [comment]
I've finished proofreading and made suggestions in the comms-edits branch
